name: Release CI

on: 
  release:
    types: [published]
    branches: 
      - master

env:
  DEBUG: 1
  NODE_ENV: development

jobs:
  test:
    name: Publish
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        node: ['12']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install Node Modules
        run: npm install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
