name: Trigger Release CI

on: 
  push:
    branches: 
      - master

env:
  DEBUG: 1
  NODE_ENV: development

jobs:
  test:
    name: Trigger Release
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        node: ['12']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}
      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false     
